import os
from pathlib import Path


# Secret key
SECRET_KEY = os.environ.get('FLASK_SECRET_KEY')

# Root project directory
BASEDIR = Path(__file__).parent.absolute() / '..'

FLASK_DEBUG = os.environ.get('FLASK_DEBUG')

SQLALCHEMY_DATABASE_USER = os.environ.get('SQLALCHEMY_DATABASE_USER')
SQLALCHEMY_DATABASE_PASSWORD = os.environ.get('SQLALCHEMY_DATABASE_PASSWORD')
SQLALCHEMY_DATABASE_HOST = os.environ.get('SQLALCHEMY_DATABASE_HOST')
SQLALCHEMY_DATABASE_PORT = os.environ.get('SQLALCHEMY_DATABASE_PORT')
SQLALCHEMY_DATABASE_DB = os.environ.get('SQLALCHEMY_DATABASE_DB')

SQLALCHEMY_DATABASE_URI = f'postgresql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}' \
                          f'@{SQLALCHEMY_DATABASE_HOST}:{SQLALCHEMY_DATABASE_PORT}/{SQLALCHEMY_DATABASE_DB}'

NOTES_PER_PAGE = 5
ENTRIES_PER_PAGE = 2